
<!--<header id="header">-->
    <div class="container">
      <div id="logo" class="pull-left">
        <a href="#hero"><img src="img/preloader.svg" alt="" title="" /></img></a>
        <!-- Uncomment below if you prefer to use a text image -->
        <!--<h1><a href="#hero">Header 1</a></h1>-->
      </div>
        
      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="#hero">Home</a></li>
          <li><a href="#about">About Me</a></li>
          <li><a href="#projects">Class Files</a></li>
          <!--<li><a href="#testimonials">Cool Math Stuff</a></li>-->
          <!--<li><a href="#team">Team</a></li>-->
          <li><a href="https://dsherma7.github.io/projects/projects.html" >My Projects</a>
            <ul>
              <li><a href="https://github.com/dsherma7/Humidor" >Humidor</a></li>
              <li class="menu-has-children"><a href="https://dsherma7.github.io/projects/mathnet/mathnet.html" >Mathnet</a>
                <ul>                  
                  <li><a href="https://dsherma7.github.io/projects/mathnet/mathnet.html#powerpoint" >Overview PPT</a></li>
                  <li><a href="https://dsherma7.github.io/projects/mathnet/mathnet.html#trimmer" >Trimming Tex</a></li>
                  <li><a href="https://dsherma7.github.io/projects/mathnet/mathnet.html#common_words" >Common Words</a></li>
                  <li><a href="https://dsherma7.github.io/projects/mathnet/mathnet.html#classifier" >Classifying Fields</a></li>
                  <li><a href="https://dsherma7.github.io/projects/mathnet/mathnet.html#beautiful" >Most Beautiful Theorems</a></li>
                  <li><a href="https://dsherma7.github.io/projects/mathnet/mathnet.html#unclassified" >Unclassified Theorems</a></li>
                </ul>
              </li>
              <li><a href="https://github.com/dsherma7/Computing" >Matlab Computing Scripts</a></li>
            </ul>
          </li>
          <li><a href="#contact">Contact Me</a></li>
          
          
        </ul>
      </nav><!-- #nav-menu-container -->
    </div>
  <!--</header>--><!-- #header -->
